# Generated by Django 5.2.8 on 2025-11-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Department"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE", "Employee"),
                    ("MANAGER", "Manager"),
                    ("ADMIN", "Admin"),
                ],
                default="EMPLOYEE",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
